### ISSUE TITLE
interrupt connection question

### ISSUE THREAD

**Issue by skytguuu** [jordibc/entrez#3]
Hi,

Recently, I tried to use entrez to search the articles of pubemd, however it had reported "ConnectionError", probably because of the large number of terms needed to be search. Is there a way to solve this problem?

Thanks for your help!

**Comment by jordibc** [comment]
Hi @skytguuu , sorry I didn't see this before. I actually develop this in gitlab (https://gitlab.com/jordibc/entrez/), so I wasn't even aware of open issues here!

I'm closing the issue now anyway, since the library seems to be working fine, and that was probably a problem with the query or the NCBI servers at the time.
